**To Find out correlation b/w two variable x and y if correlation is 1 it means that variable to dependable to each other we can perform this operation in order to know,whether linear regression can be applied on particular problem or not,So if it gives 1 or close to 1 so it means we can apply linear regression otherwise we can not perform it . **

In [77]:
import random
import numpy as np
x= np.arange(-10,11)

In [84]:
y = 2*x +3+np.random.randn(len(x))
y1 = 2*x**2 +3+np.random.randn(len(x))

In [85]:
#1 we have corelation and 0 for no corelation 
np.corrcoef(x,y)

array([[1.        , 0.99750032],
       [0.99750032, 1.        ]])

In [86]:
np.corrcoef(x,y1)# we cannot write as line  because we hav  low correlation 

array([[1.       , 0.0048492],
       [0.0048492, 1.       ]])

In [87]:
np.corrcoef(x**2,y1)# it means write y1 as x**2 +c 

array([[1.        , 0.99993567],
       [0.99993567, 1.        ]])