**NumpyExercise**

In [5]:
import numpy as np

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
z = np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
z[:]=5
z

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
j = np.arange(9)

In [16]:
j.reshape(3,3)# when rows*columns = no of element then only it will give us solution

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array(np.random.random())

array(0.68341135)

In [21]:
np.random.randn(25)

array([ 1.28019005, -1.07842285,  0.87938096,  0.84965746, -1.1440428 ,
       -0.7232789 ,  0.54786588,  0.16658415, -0.13110896,  1.45681977,
       -0.44182117, -0.10639125, -0.23838288, -1.20912993, -0.38044887,
       -0.70172815,  0.58913893, -1.06670452,  0.12295146,  0.13091969,
        2.80136135,  2.10548322, -1.23370578, -1.50633046, -0.34382735])

In [27]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [26]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[3,4]

20

In [50]:
mat[:3,1]

array([ 2,  7, 12])

In [51]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [52]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
np.sum(mat)

325

In [57]:
mat.var()**0.5

7.211102550927978

In [58]:
mat.std()

7.211102550927978

In [64]:
np.sum(mat,axis=0) # axis = 0 for column 

array([55, 60, 65, 70, 75])

In [65]:
np.sum(mat,axis=1)# axis = 1 for rows 

array([ 15,  40,  65,  90, 115])

In [84]:
j=np.arange(9)
s = j.reshape(3,3)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
k = np.arange(2,19,2)
print(k)


[ 2  4  6  8 10 12 14 16 18]


In [87]:
z=s+l
z

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [92]:
b = np.random.randint(0,7,5)
b

array([1, 4, 4, 1, 6])

In [95]:
k[b]=k[b]+1

In [96]:
k

array([ 2,  5,  6,  8, 11, 12, 15, 16, 18])

In [121]:
z = np.arange(0,16)
i = z.reshape(2,2,2,2)
i

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [122]:
i.sum(axis=(-1,-2))

array([[ 6, 22],
       [38, 54]])

In [137]:
i[1,1,:,:]#for confiming for element 0,0_0,1_,1,0_1,1

array([[12, 13],
       [14, 15]])

In [183]:
i = np.arange(0,4).reshape(2,2)
i

array([[0, 1],
       [2, 3]])

In [184]:
i[[0,1],:] = i[[1,0],:]

In [185]:
i

array([[2, 3],
       [0, 1]])

In [196]:
import numpy as np
np.arange(2,15,2)# 3rd argument will give us that much step

array([ 2,  4,  6,  8, 10, 12, 14])

In [197]:
np.linspace(2,15,10)# 3rd argument will give that much evenly  step b/w start and stop points.

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

In [198]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [199]:
np.random.rand(2)

array([0.53774845, 0.48270676])

In [200]:
np.random.randn(4,4)# it give us from normal distribution

array([[-0.52138268,  0.00166139, -0.53336864,  1.45097228],
       [-1.0184879 , -1.3828949 , -0.08232064,  0.19681648],
       [-0.04949201, -0.62538375,  0.50586758, -1.09448705],
       [ 0.44320927, -0.48732057, -0.18362671,  1.13385061]])

In [201]:
np.random.randint(1,100,10)# 3rd argument will give us no of  element

array([23, 21,  2, 95, 94, 71, 59, 70, 81, 62])

In [202]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [203]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [204]:
arr.min()

0

In [205]:
arr.max()

24

In [206]:
arr.argmax()# give us index of max number

24

In [207]:
arr.argmin() # give us the index of min number

0

In [208]:
arr.dtype

dtype('int32')

In [209]:
arr.shape

(25,)

In [210]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [211]:
arr.shape

(25,)

In [212]:
from numpy.random import randint

In [213]:
arr_cp = arr.copy()

In [214]:
randint(10)

3

In [215]:
arr[23]

23

In [216]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [217]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [218]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [219]:
arr[15:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [220]:
arr[:5]=100

In [221]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [222]:
arr_cp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [223]:
arr_cp[:]=13

In [224]:
arr_cp

array([13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13])

In [225]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [226]:
arr[arr>30]

array([100, 100, 100, 100, 100])

In [227]:
np.sqrt(arr)

array([10.        , 10.        , 10.        , 10.        , 10.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949])

In [228]:
np.exp(arr)

array([2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43,
       2.68811714e+43, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [229]:
np.max(arr)

100